# Generated by Django 3.1.8 on 2021-04-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210413_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
