# Generated by Django 3.1.8 on 2021-04-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(blank=True, null=True, to='users.Address'),
        ),
    ]
